version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: g4-db-server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - /srv/g4/db/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: g4-db-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    expose:
      - "80"
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: g4-metabase
    hostname: g4-metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 5002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: g4-db-server
    restart: unless-stopped

networks:
  default:
      name: pws_frontend_default
      external: true

