version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: g4-db-app
    environment:
      POSTGRES_USER: g4
      POSTGRES_PASSWORD: g4g4g4
      POSTGRES_DB: eltransportador
    expose:
      - "5432"
    volumes:
      - /srv/g4/db/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: g4-db-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: db@g4.loge.ar
      PGADMIN_DEFAULT_PASSWORD: g4g4g4
    expose:
      - "80"
    restart: unless-stopped

networks:
  default:
      name: pws_frontend_default
      external: true

